### ISSUE TITLE
how to use gff3_sp_statistics.pl to statistics output from cufflinks(transcripts.gff3)

### ISSUE THREAD

**Issue by wuxiaopei0509** [NBISweden/GAAS#25]
Hi,Juke
I want to use the gff3_sp_statistics.pl to statistics the ouput from cufflinks.that is transcripts.gff3.How can I  achieve it？

Thanks！

**Comment by Juke34** [comment]
I moved gff scripts into [AGAT](https://github.com/NBISweden/AGAT/blob/master/README.md). You will find up-to-date version there, and easy installation using Conda.
