### ISSUE TITLE
missing perl module: 'NBIS::GFF3::Omniscient'

### ISSUE THREAD

**Issue by XClaws** [NBISweden/GAAS#26]
Dear team,

I am trying to use gff3_sp_fix_feature_duplication.pl, and I encountered the following error.
Can't locate NBIS/GFF3/Omniscient.pm in @INC (you may need to install the NBIS::GFF3::Omniscient module)
However, I can never find and install this module either by CPAN website or cpanm.
Could you please help me to solve this problem?
Thank you very much and happy Christmas!

Kind regards,

Wei

**Comment by XClaws** [comment]
Dear team,

I figured out how to solve the problem.
Thank you!

**Comment by Juke34** [comment]
The easiest is to use the corresponding tool in [AGAT](https://github.com/NBISweden/AGAT) `agat_sp_fix_features_locations_duplicated.pl`. AGAT can be easily installed using Conda.

**Comment by XClaws** [comment]
Thank you for your quick response!
I will try your suggestion too!
