### ISSUE TITLE
run agat_convert_sp_gff2gtf.pl after conda install

### ISSUE THREAD

**Issue by Diango700** [NBISweden/GAAS#29]
I have use this command below :
1 - conda activate agat
2 - I'm open a terminal on my gff pathway
3 - perl agat_convert_sp_gff2gtf.pl --gff  file.gff -o file.gtf

ERROR : Can't locate Sort/Naturally.pm in @INC (you may need to install the Sort::Naturally module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/kali/AGAT/bin/agat_convert_sp_gff2gtf.pl line 7.
BEGIN failed--compilation aborted at /home/kali/AGAT/bin/agat_convert_sp_gff2gtf.pl line 7.

If anyone has an idea what it is

**Comment by Juke34** [comment]
did you create the environment and install agat properly before?
```
conda create -n agat
conda activate agat
conda install -c bioconda agat
```

then the command would be 
`agat_convert_sp_gff2gtf.pl --gff file.gff -o file.gtf` no need to precise perl

**Comment by Diango700** [comment]
yes like ;
conda create --name agat

but same error

**Comment by Juke34** [comment]
Ok you have a Conda env called agat 
step1 you have created it with the command 
`
conda create --name agat
`
and step2 activated it with the command 
`
conda activate agat
`

But the error message says that prerequisites (e.g Sort/Naturally.pm) is not installed while they are supposed to be installed by conda. So apparently either you forgot the step in which you have to install agat `conda install -c bioconda agat` either during this installation conda threw an error message...

It seems you did a clone of the repo and try to run directly the script without having installed any prerequisite.

**Comment by Diango700** [comment]
I try to re-install

**Comment by Diango700** [comment]
thank you so much Juke34 !
its ok now
