### ISSUE TITLE
gff3_sp_manage_functional_annotation.pl

### ISSUE THREAD

**Issue by papelypluma** [NBISweden/GAAS#44]
Dear GAAS Developers,

I installed GAAS through Conda. I was looking for the script "gff3_sp_manage_functional_annotation.pl" to merge/integrate InterProScan output with Maker's gff3 file, but I couldn't find (invoke) it. I was wondering if this script is available separately elsewhere. 

Thank in advance for the help!

**Comment by Juke34** [comment]
Hi, thank you for using our tools.
All gff related script has been moved into [AGAT](https://github.com/NBISweden/AGAT).
This  script is now called `agat__sp_manage_functional_annotation.pl`

Best,

Jacques

**Comment by papelypluma** [comment]
Thanks for the help @Juke34!
