### ISSUE TITLE
groovy

### ISSUE THREAD

**Issue by PycnopodiaD** [NBISweden/GAAS#5]
Hi 

i) When I run this on rackham I get this error:

`$source GAAS/profiles/activate_nbis_env
Admin privileges not granted
Checking for tool dependencies
Ruby is installed ... yes : ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
Groovy is installed ... no
Perl is installed ... yes : 
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Rscript is installed ... yes : Fatal error: cannot open file '-v': No such file or directory
make: *** [check] Error 2`

ii) When I run it on my own server (Ubuntu server 18.04 LTS), which has groovy installed I get:

`Fatal error: cannot open file '-v': No such file or directory
~/Makefile:2: recipe for target 'check' failed
make: *** [check] Error 2`

Any thoughts?

**Comment by mahesh-panchal** [comment]
Hi,

That's a copy-paste bug when doing the version check for Rscript. 
The makefile should have `Rscript --version` rather than `Rscript -v`.

I've updated the code. Thanks for reporting it.

Regards,
