### ISSUE TITLE
Versioning is not correct.

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/GAAS#53]
The versioning is not correct in `gaas_fasta_removeSeqFromIDlist.pl`

How to reproduce:
```
docker run -it --rm quay.io/biocontainers/gaas:1.2.0--pl526r35_0 bash
gaas_fasta_removeSeqFromIDlist.pl --help
```

Output:
```

 ------------------------------------------------------------------------------
|   Genome Assembly Annotation Service (AGAT) - Version: v1.1.0              |
|   https://github.com/NBISweden/AGAT                                          |
|   National Bioinformatics Infrastructure Sweden (NBIS) - www.nbis.se         |
 ------------------------------------------------------------------------------
  
< truncated >
```

General problem:
I need to be able to extract version information reliably when using these scripts in the nf-core modules way.

**Comment by Juke34** [comment]
It is here https://github.com/NBISweden/GAAS/blob/master/lib/GAAS/GAAS.pm
I had changed AGAT by GAAS (obvious error) but didn't change the version...
You should release a new version v1.2.1
