### ISSUE TITLE
Bug in gaas_filter_by_size.pl

### ISSUE THREAD

**Issue by marchoeppner** [NBISweden/GAAS#61]
Hi,

in: gaas_filter_by_size.pl

you guys are not actually using the "-o" option to designate an output file. And in addition, the line used to name the output file has an error in the regexp:

/.fa/ -> should be /\\.fa/

However, I was actually annotating some dog data, with the file name "Canis_familiaris.proteins.fa" - and that actually produced:

Canisamiliaris.proteins.30.fa

Obviously, this is a problem for nextflow or other tools using name tracking. So maybe just use the "-o" option so users can choose the name.

**Comment by Juke34** [comment]
Hi, 
Yes changing the ouput file was bad bad bad.... my fault I remove it. But to go from `Canis_familiaris.proteins.fa` to `Canisamiliaris.proteins.30.fa` I don't see. It is probably not that script...
Could you check?

**Comment by marchoeppner** [comment]
Thanks!

I think the naming issues comes from the regexp. The way is written now is "any character followed by 'fa'. It should be "dot character followd by fa" - so the dot needs to be escaped. 

Anyway, thanks for fixing it!

**Comment by Juke34** [comment]
Oh Yes I didn't see the `fa` from `familiaris` removed, I was looking at the `.proteins.30` that was added ^^
