### ISSUE TITLE
GXF Handler - When parsing using locus tag - duplicate are not removed.

### ISSUE THREAD

**Issue by Juke34** [NBISweden/GAAS#7]
see RAST gff annotation

**Comment by sanyalab** [comment]
While running "gff3_sp_keep_longest_isoform.pl" I am getting the following error
`Can't use an undefined value as an ARRAY reference at /anno/sanyalab/SOFTWARE/GAAS/annotation/BILS/Handler/GXFhandler.pm line 1293`

I have attached a small chunk of the file giving the problem. Please advice.
[ptn_genes_modi.txt](https://github.com/NBISweden/GAAS/files/3111798/ptn_genes_modi.txt)

**Comment by Juke34** [comment]
fixed
