### ISSUE TITLE
Better description of statistics module

### ISSUE THREAD

**Issue by sanyalab** [NBISweden/GAAS#8]
Hello,

I was wondering if you could help me understand some of the stats generated by GAAS module gff3_sp_statistics.pl. 

1) What do you mean by "Number of intron in cds" and "Number of intron in exon". I am confused. How can introns exist in exons.
2) While calculating "Number of cdss", "Number of exons", "Number of exon in cds", "mean exons per mrna" "Total mrna length" "Total cds length" "Total exon length" do you consider all transcripts for a gene or the longest transcript for a gene.
3) "Total intron length per cds", "Total intron length per exon", "Total intron length per five_prime_utr", "Total intron length per three_prime_utr" is unnaturally high. What is meant by these?
4) What is the difference between "mean cds length" and "mean cds piece length"
5) What is the difference between "mean five_prime_utr length" and "mean five_prime_utr piece length"

Please give a better description of the stats. Attached is a stat file I generated
Thank you
Abhijit
[test_stat_gaas.txt](https://github.com/NBISweden/GAAS/files/3109551/test_stat_gaas.txt)

**Comment by Juke34** [comment]
Hi,
1. In the following case where you have 5 exon (3 are UTRs and 2 are CDS) 
'==UTR exon==intron==UTR exon==intron==CDS exon==intron==CDS exon==intron==UTR exon=='   
the mRNA has 4 introns, while the CDS which can be spread over several exon (as in this case) has 1 introns. The `Number of intron in cds` corresponds to this last information.  

2. I do both. When there is isoforms, the statistics will be written twice, first with all isoforms, then we remove informs keeping only the longest per gene and recalculate the statistics.
In such case you will have a bench of statistics, then a sentence like:  
 `Apparently we have isoforms : Number level1 features: X / Number of level2 features: YY
We will proceed to the statistics analysis using only the mRNA with the longest cds`  
then a bench of new statistics again.

3. Why unnaturally high? What do you expect ? In the first part of your statistics isoforms are counted, it's maybe why you see that such high.

4. "mean cds length" is the whole CDS even if it is spread over several exons, while `mean cds piece length` is only looking at each piece/CDS-exon.

5. The same as for CDS i.e point 4

**Comment by sanyalab** [comment]
Thank you Jacques. Very nice script indeed. Much more detailed stats compared to GAG. Plus you do not need a genome sequence. Can you add the following in later versions

1) Number of overlapping genes
2) Number of Contained genes

Best Regards

**Comment by Juke34** [comment]
You're welcome. Thx.
I will think about it but it's not a priority.
What do you mean by 'Contained genes' ? Is it a gene that is fully overlapped by another one ?
