### ISSUE TITLE
agat_sp_manage_functional_annotation.pl formatting issue

### ISSUE THREAD

**Issue by JuliaLopezDelgado** [NBISweden/GAAS#84]
Hello,

I installed AGAT using bioconda. I am trying to run the following: `agat_sp_manage_functional_annotation.pl -gff braker1+2_combined.gtf -i genome_AA.faa.tsv -o braker.interproscan`

The input GTF file is the output of the TSEBRA combiner tool that combines the predictions from Braker1 and Braker2. I am getting the error:
```=> GFF parser version used: 2
gff3 reader error level1: No ID attribute found @ for the feature: scf7180000002648     AUGUSTUS        gene    57422     208439  .       +       .
gff3 reader error level2: No ID attribute found @ for the feature: scf7180000002648     AUGUSTUS        transcript57422   208439  .       +       .
WARNING level2: No Parent attribute found @ for the feature: scf7180000002648   AUGUSTUS        transcript      57422     208439  .       +       .       ID "transcript-1"
WARNING gff3 reader: Hmmm, be aware that your feature doesn't contain any Parent and locus tag. No worries, we will handle it by considering it as strictly sequential. If you disagree, please provide an ID or a comon tag by locus. @ the feature is:
```

I saw other people had issues with TSEBRA output formatting, so I ran the rename_gtf.py script to clean up the gtf file but the error persists. 

Here are the top lines of the 'clean' gtf file:
```scf7180000002648       AUGUSTUS        gene    57422   208439  .       +       .       g1
scf7180000002648        AUGUSTUS        transcript      57422   208439  .       +       .       g1.t1
scf7180000002648        AUGUSTUS        start_codon     57422   57424   .       +       0       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        CDS     57422   57455   0.38    +       0       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        exon    57422   57455   .       +       .       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        intron  57456   74207   0.54    +       .       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        CDS     74208   74305   0.54    +       2       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        exon    74208   74305   .       +       .       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        intron  74306   75613   0.53    +       .       transcript_id "g1.t1"; gene_id "g1";
scf7180000002648        AUGUSTUS        CDS     75614   75730   0.56    +       0       transcript_id "g1.t1"; gene_id "g1";
```

Do you have any suggestions on how to fix this?

Thanks in advance!
Julia

**Comment by Juke34** [comment]
Hi, any reason you opened the issue in the GAAS repo rather the AGAT repo?

No worries, they are just warning. Indeed for many years Augustus and subsequent tools as TSEBRA create feature without mandatory attributes requested by the format (here the transcript feature line).  
 AGAT handles this perfectly well.  
In such case AGAT uses a `sequential` approach, which means all level3 features (exon, CDS...) are llinked o the last level2 feature (transcript) met when reading the file from top to bottom.
Look at the output for the example you provided, you will see it should be fine.

**Comment by JuliaLopezDelgado** [comment]
Hello,

Sorry for posting on the wrong repo!

Thanks for letting me know about the warning. It does seem like it ran okay when I check the output folder. 

Many thanks,
Julia
